name: truck
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

dependencies:
  args: ^2.5.0
  collection: ^1.18.0
  http: ^1.2.1
  googleapis_auth: ^1.6.0
  googleapis: ^13.1.0
  meta: ^1.14.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^3.0.0
  parameterized_test: ^2.0.0
  test: ^1.25.4
  very_good_analysis: ^5.1.0
